;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        meow-append
        meow-back-word
        meow-cancel-selection
        meow-find
        meow-insert
        meow-insert-exit
        meow-left
        meow-right
        meow-undo
        ))

(setq mc/cmds-to-run-once
      '(
        puni-backward-delete-char
        ))
