"ui.background" = { bg = "black1" }
"ui.background.separator" = { fg = "black4" }

"ui.text" = "light2"
"ui.selection" = { bg = "black4" }

"ui.cursor" = { bg = "orange2", fg = "black1" }
"ui.cursor.normal" = { bg = "orange2" }
"ui.cursor.insert" = { fg = "orange2", bg = "orange2" }
"ui.cursor.select" = { bg = "orange2", fg = "black1"  }
"ui.cursor.match" = { bg = "orange2", fg = "black1" }
"ui.cursorline.primary" = { bg = "black2" }

"ui.linenr" = { fg = "black5" }
"ui.linenr.selected" = { fg = "orange2" }

"ui.statusline" = { fg = "black5", bg = "black2" }
"ui.statusline.normal" = { fg = "orange3", bg = "orange1" } 
"ui.statusline.insert" = { fg = "blue3", bg = "blue1" } 
"ui.statusline.select" = { fg = "lightgreen", bg = "green2" } 
"ui.help" = { fg = "light2", bg = "black2" }
"ui.window" = { fg = "black4" }

"ui.popup" = { fg = "light2", bg = "black2" }
"ui.menu" = { fg = "light2", bg = "black2" }
"ui.menu.selected" = { fg = "black2", bg = "orange2" }

"error" = { fg = "red1" }
"warning" = { fg = "orange2" }
"info" = { fg = "blue5" }
"hint" = { fg = "blue5" }
"diagnostic" = { modifiers = ["underlined"] }

"diff.plus.gutter" = { fg = "green1" }
"diff.minus.gutter" = { fg = "pink" }
"diff.delta" = { fg = "blue5" }

# ---------- LSP ----------
"comment" = { fg = "black5" }
"type" = { fg = "blue5" }
"string" = { fg = "orange3" }
"string.regexp" = { fg = "black6" }
"string.special" = { fg = "blue5" }
"constant" = { fg = "blue5" }
"variable" = { fg = "light2" }
"variable.builtin" = { fg = "blue5" }
"punctuation" = { fg = "light2" }
"function" = { fg = "purple1" }
"operator" = { fg = "pink" }
"special" = { fg = "blue5" }
"keyword" = { fg = "pink" }


[palette]
black1  = "#0e100f"
black2  = "#1e201f"
black3  = "#1f211f"
black4  = "#403e3c"
black5  = "#878580"
black6  = "#a0a0a0"

light1  = "#f8f8f8"
light2  = "#cecdc3"
light3  = "#fefefe"

blue1   = "#2b5375"
blue2   = "#3aa99f"
blue3   = "#4385be"
blue4   = "#5b79e3"
blue5   = "#79b8ff"
blue6   = "#8caec1"

lightgreen = "#a9be50"
green1  = "#879a39"
green2  = "#6c7b2e"

yellow1 = "#ad8301"
yellow2 = "#d0a215"
yellow3 = "#f3cd07"

orange1 = "#da702c"
orange2 = "#fe9900"
orange3 = "#ffab70"
orange4 = "#ffc799"

purple1 = "#b392f1"
purple2 = "#e394dc"
purple3 = "#834de8"

pink    = "#fa7584"
pink2   = "#f84055"

red1    = "#d14d41"
red2    = "#d3604f"

