inherits = "material_darker"

"ui.background" = { bg = "dark_default", fg = "dark_second" }
"ui.cursor.primary" = { bg = "yellow", fg = "dark_default" }
"ui.cursorline.primary" = { bg = "dark_second", fg = "grey" }

"ui.background.separator" = { fg = "dark_second" }
"ui.window" = "dark_second"

"ui.popup" = { fg = "dark_second" }
"ui.help" = { bg = "dark_default" }

"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.info" = { underline = { color = "#82AAFF", style = "curl" } }
"diagnostic.hint" = { underline = { color = "#82AAFF", style = "curl" } }

[palette]
dark_default = "#151515"
dark_second = "#303030"
grey = "#333333"
yellow = "#FFCA41"
