format = "$all$line_break$jobs$character"

[username]
show_always = false
format = '[$user](green)'

[character]
success_symbol = '[└](lightgray) [λ](bold green)' 
error_symbol = '[└](lightgray) [λ](bold red)' 

[time]
disabled = false
style = 'fg:#403e3c'
format = '· [$time]($style)'

[cmd_duration]
disabled = true

# Packages and symbols
[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "
format = '—  [$symbol($version )]($style)'

[conda]
symbol = " "
format = '—  [$symbol($version )]($style)'

[dart]
symbol = " "
format = '—  [$symbol($version )]($style)'

[directory]
read_only = " 󰌾"
style = 'fg:#79b8ff'
format = "┌ [$path]($style) "

[docker_context]
symbol = " "

[elixir]
symbol = " "
format = '—  [$symbol($version )]($style)'

[elm]
symbol = " "
format = '—  [$symbol($version )]($style)'

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "
format = '—  [$symbol($version )]($style)'

[guix_shell]
symbol = " "
format = '—  [$symbol($version )]($style)'

[haskell]
symbol = " "
format = '—  [$symbol($version )]($style)'

[haxe]
symbol = " "
format = '—  [$symbol($version )]($style)'

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "
style = 'fg:green'
ssh_only = true
format = '@[hostname]($style)'

[java]
symbol = " "
format = '—  [$symbol($version )]($style)'

[julia]
symbol = " "
format = '—  [$symbol($version )]($style)'

[lua]
symbol = " "
format = '—  [$symbol($version )]($style)'

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "
format = '—  [$symbol($version )]($style)'


[nix_shell]
symbol = " "

[nodejs]
symbol = " "
format = '—  [$symbol($version )]($style)'


[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "
format = '—  [$symbol($version )]($style)'


[rlang]
symbol = "󰟔 "
format = '—  [$symbol($version )]($style)'


[ruby]
symbol = " "
format = '—  [$symbol($version )]($style)'


[rust]
symbol = " "
format = '—  [$symbol($version )]($style)'


[scala]
symbol = " "
format = '—  [$symbol($version )]($style)'

