[window]
decorations_theme_variant = "Dark"
padding = {x = 6, y = 0}

[font]
size = 11
normal = { family = "ZedMono Nerd Font" }
# normal = { family = "UDEV Gothic NF" }

[colors.primary]
# background = "#0E100F"
# foreground = "#CECDC3"

background = "#FEFEFE"
foreground = "#0E100F"

[colors.normal]
black = "#0E100F"
red = "#D14D41"
green = "#879A39"
yellow = "#F3CD07"
blue = "#5B79E3"
magenta = "#E394DC"
cyan = "#3AA99F"
white = "#FFFFFF"
