(deftheme mod-tangonov
  "A 256 color dark theme featuring bright pastels.")

(custom-theme-set-faces
 'mod-tangonov
 '(ansi-color-black ((((class color) (min-colors 256)) (:foregound "#303030" :background "#303030"))))
 '(ansi-color-blue ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#82AAFF"))))
 '(ansi-color-bright-black ((((class color) (min-colors 256)) (:foreground "#626262" :background "#626262"))))
 '(ansi-color-bright-blue ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#82AAFF"))))
 '(ansi-color-bright-cyan ((((class color) (min-colors 256)) (:foreground "#89DDFF" :background "#89DDFF"))))
 '(ansi-color-bright-green ((((class color) (min-colors 256)) (:foreground "#ABDC88" :background "#ABDC88"))))
 '(ansi-color-bright-magenta ((((class color) (min-colors 256)) (:foreground "#C792EA" :background "#C792EA"))))
 '(ansi-color-bright-red ((((class color) (min-colors 256)) (:foreground "#FF7B85" :background "#FF7B85"))))
 '(ansi-color-bright-white ((((class color) (min-colors 256)) (:foreground "#FFFFFF" :background "#FFFFFF"))))
 '(ansi-color-bright-yellow ((((class color) (min-colors 256)) (:foreground "#FFCA41" :background "#FFCA41"))))
 '(ansi-color-cyan ((((class color) (min-colors 256)) (:foreground "#89DDFF" :background "#89DDFF"))))
 '(ansi-color-green ((((class color) (min-colors 256)) (:foreground "#ABDC88" :background "#ABDC88"))))
 '(ansi-color-magenta ((((class color) (min-colors 256)) (:foreground "#C792EA" :background "#C792EA"))))
 '(ansi-color-red ((((class color) (min-colors 256)) (:foreground "#FF7B85" :background "#FF7B85"))))
 '(ansi-color-white ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :background "#EEFFFF"))))
 '(ansi-color-yellow ((((class color) (min-colors 256)) (:foreground "#FFCA41" :background "#FFCA41"))))
 '(anzu-mode-line ((((class color) (min-colors 256)) (:foreground "#FFCA41" :weight bold))))
 '(anzu-mode-line-no-match ((((class color) (min-colors 256)) (:foreground "#FF7B85" :weight bold))))
 '(anzu-replace-highlight ((((class color) (min-colors 256)) (:foreground "#FFCA41" :background "#4c3c13" :strike-through t))))
 '(anzu-replace-to ((((class color) (min-colors 256)) (:foreground "#89DDFF" :background "#446e7f"))))
 '(avy-goto-char-timer-face ((((class color) (min-colors 256)) (:inherit 'isearch))))
 '(avy-background-face ((((class color) (min-colors 256)) (:foreground "#101010"))))
 '(avy-lead-face ((((class color) (min-colors 256)) (:foreground "#FF7B85" :weight bold))))
 '(avy-lead-face-0 ((((class color) (min-colors 256)) (:inherit 'avy-lead-face :foreground "#FFCA41"))))
 '(avy-lead-face-1 ((((class color) (min-colors 256)) (:inheri avy-lead-face :foreground "#997926"))))
 '(avy-lead-face-2 ((((class color) (min-colors 256)) (:inherit 'avy-lead-face :foreground "#66501a"))))
 '(company-echo-common ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(company-preview ((((class color) (min-colors 256)) (:inherit 'highlight :foreground "#BFC7D5"))))
 '(company-preview-common ((((class color) (min-colors 256)) (:inherit 'company-preview :foreground "#C792EA"))))
 '(company-preview-search ((((class color) (min-colors 256)) (:inherit 'company-preview :foreground "#89DDFF"))))
 '(company-scrollbar-bg ((((class color) (min-colors 256)) (:background "#202020"))))
 '(company-scrollbar-fg ((((class color) (min-colors 256)) (:background "#C792EA"))))
 '(company-template-field ((((class color) (min-colors 256)) (:background "#FFCA41" :foreground "#151515"))))
 '(company-tooltip ((((class color) (min-colors 256)) (:background "#151515"))))
 '(company-tooltip-annotation ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(company-tooltip-common ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 256)) (:foreground "#ABDC88" :weight bold))))
 '(company-tooltip-scrollbar-thumb ((((class color) (min-colors 256)) (:background "#BB80B3"))))
 '(company-tooltip-scrollbar-track ((((class color) (min-colors 256)) (:background "#202020"))))
 '(company-tooltip-selection ((((class color) (min-colors 256)) (:inherit bold :background "#303030"))))
 '(corfu-current ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :background "#303030" :weight normal))))
 '(css-proprietary-property ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(css-property ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(css-selector ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(custom-button ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#151515" :box '(:line-width 1 :style none)))))
 '(custom-button-unraised ((((class color) (min-colors 256)) (:foreground "#BB80B3" :background "#151515" :box '(:line-width 1 :style none)))))
 '(custom-button-pressed-unraised ((((class color) (min-colors 256)) (:foreground "#151515" :background "#BB80B3" :box '(:line-width 1 :style none)))))
 '(custom-button-pressed ((((class color) (min-colors 256)) (:foreground "#151515" :background "#82AAFF" :box '(:line-width 1 :style none)))))
 '(custom-button-mouse ((((class color) (min-colors 256)) (:foreground "#151515" :background "#82AAFF" :box '(:line-width 1 :style none)))))
 '(custom-variable-button ((((class color) (min-colors 256)) (:foreground "#ABDC88" :underline t))))
 '(custom-saved ((((class color) (min-colors 256)) (:foreground "#ABDC88" :background "#556e44" :bold bold))))
 '(custom-comment ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(custom-comment-tag ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(custom-modified ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#41557f"))))
 '(custom-variable-tag ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(custom-visibility ((((class color) (min-colors 256)) (:foreground "#82AAFF" :underline nil))))
 '(custom-group-subtitle ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(custom-group-tag ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(custom-group-tag-1 ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(custom-set ((((class color) (min-colors 256)) (:foreground "#FFCA41" :background "#151515"))))
 '(custom-themed ((((class color) (min-colors 256)) (:foreground "#FFCA41" :background "#151515"))))
 '(custom-invalid ((((class color) (min-colors 256)) (:foreground "#FF7B85" :background "#7f3d42"))))
 '(custom-variable-obsolete ((((class color) (min-colors 256)) (:foreground "#626262" :background "#151515"))))
 '(custom-state ((((class color) (min-colors 256)) (:foreground "#ABDC88" :background "#556e44"))))
 '(custom-changed ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#151515"))))
 '(elfeed-log-debug-level-face ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(elfeed-log-error-level-face ((((class color) (min-colors 256)) (:inherit 'error))))
 '(elfeed-log-info-level-face ((((class color) (min-colors 256)) (:inherit 'success))))
 '(elfeed-log-warn-level-face ((((class color) (min-colors 256)) (:inherit 'warning))))
 '(elfeed-search-date-face ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(elfeed-search-feed-face ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(elfeed-search-tag-face ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(elfeed-search-title-face ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(elfeed-search-filter-face ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(elfeed-search-unread-count-face ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(elfeed-search-unread-title-face ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :weight bold))))
 '(eww-form-checkbox ((((class color) (min-colors 256)) (:inherit 'eww-form-file))))
 '(eww-form-file ((((class color) (min-colors 256)) (:inherit 'eww-form-submit :background "#202020"))))
 '(eww-form-select ((((class color) (min-colors 256)) (:inherit 'eww-form-submit :background "#202020"))))
 '(eww-form-submit ((((class color) (min-colors 256)) (:inherit 'eww-form-text :box `(:line-width 2 :style released-button) :background "#303030"))))
 '(eww-form-text ((((class color) (min-colors 256)) (:box `(:line-width 1 :color ,gray2) "#151515" :foreground "#EEFFFF" :distant-foreground "#151515"))))
 '(eww-form-textarea ((((class color) (min-colors 256)) (:inherit 'eww-form-text))))
 '(eww-invalid-certificate ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(eww-valid-certificate ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(bold ((((class color) (min-colors 256)) (:weight bold))))
 '(italic ((((class color) (min-colors 256)) (:slant italic))))
 '(bold-italic ((((class color) (min-colors 256)) (:weight bold :slant italic))))
 '(underline ((((class color) (min-colors 256)) (:underline t))))
 '(shadow ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(link ((((class color) (min-colors 256)) (:foreground "#82AAFF" :weight bold :underline t))))
 '(link-visited ((((class color) (min-colors 256)) (:inherit 'link :foreground "#C792EA"))))
 '(highlight ((((class color) (min-colors 256)) (:background "#303030" :weight normal))))  ;; can be set to bold
 '(match ((((class color) (min-colors 256)) (:foreground "#ABDC88" :background "#556e44"))))
 '(region ((((class color) (min-colors 256)) (:foreground "#89DDFF" :background "#446e7f"))))
 '(secondary-selection ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :background "#303030"))))
 '(lazy-highlight ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#41557f"))))
 '(error ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(warning ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(success ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(escape-glyph ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(homoglyph ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(vertical-border ((((class color) (min-colors 256)) (:foreground "#303030"))))
 '(cursor ((((class color) (min-colors 256)) (:background "#FFCA41"))))
 '(minibuffer-prompt ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(line-number-current-line ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(completions-common-part ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(completions-first-difference ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(completions-annotations ((((class color) (min-colors 256)) (:foreground "#FFCA41" :weight bold))))
 '(trailing-whitespace ((((class color) (min-colors 256)) (:background "#FF7B85"))))
 '(whitespace-trailing ((((class color) (min-colors 256)) (:background "#FF7B85"))))
 '(bookmark-face ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(tool-bar ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :background "#202020"))))
 '(tooltip ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :background "#202020"))))
 '(message-header-name ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(message-header-subject ((((class color) (min-colors 256)) (:foreground "#89DDFF" :weight bold))))
 '(message-header-to ((((class color) (min-colors 256)) (:foreground "#89DDFF" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 256)) (:inherit 'message-header-to :foreground "#74bbd8"))))
 '(message-header-other ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(message-header-newsgroups ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(message-header-xheader ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(message-separator ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(message-mml ((((class color) (min-colors 256)) (:foreground "#626262" :slant italic))))
 '(gnus-group-mail-1 ((((class color) (min-colors 256)) (:weight bold :foreground "#EEFFFF"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1))))
 '(gnus-group-mail-3 ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1))))
 '(gnus-group-mail-1-empty ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(gnus-group-mail-2-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1-empty))))
 '(gnus-group-mail-3-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1-empty))))
 '(gnus-group-news-1 ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1))))
 '(gnus-group-news-2 ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1))))
 '(gnus-group-news-3 ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1))))
 '(gnus-group-news-4 ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1))))
 '(gnus-group-news-5 ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1))))
 '(gnus-group-news-6 ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1))))
 '(gnus-group-news-1-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1-empty))))
 '(gnus-group-news-2-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1-empty))))
 '(gnus-group-news-3-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1-empty))))
 '(gnus-group-news-4-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1-empty))))
 '(gnus-group-news-5-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1-empty))))
 '(gnus-group-news-6-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-1-empty))))
 '(gnus-group-mail-low ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1 :weight normal))))
 '(gnus-group-mail-low-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1-empty))))
 '(gnus-group-news-low ((((class color) (min-colors 256)) (:inherit 'gnus-group-mail-1 :foreground "#A8A8A8"))))
 '(gnus-group-news-low-empty ((((class color) (min-colors 256)) (:inherit 'gnus-group-news-low :weight normal))))
 '(gnus-header-content ((((class color) (min-colors 256)) (:inherit 'message-header-other))))
 '(gnus-header-from ((((class color) (min-colors 256)) (:inherit 'message-header-other))))
 '(gnus-header-name ((((class color) (min-colors 256)) (:inherit 'message-header-name))))
 '(gnus-header-newsgroups ((((class color) (min-colors 256)) (:inherit 'message-header-other))))
 '(gnus-header-subject ((((class color) (min-colors 256)) (:inherit 'message-header-subject))))
 '(gnus-summary-cancelled ((((class color) (min-colors 256)) (:foreground "#FF7B85" :strike-through t))))
 '(gnus-summary-high-ancient ((((class color) (min-colors 256)) (:foreground "#b9b9b9" :inherit 'italic))))
 '(gnus-summary-high-read ((((class color) (min-colors 256)) (:foreground "#f1ffff"))))
 '(gnus-summary-high-ticked ((((class color) (min-colors 256)) (:foreground "#d2a7ee"))))
 '(gnus-summary-high-unread ((((class color) (min-colors 256)) (:foreground "#bbe39f"))))
 '(gnus-summary-low-ancient ((((class color) (min-colors 256)) (:foreground "#868686" :inherit 'italic))))
 '(gnus-summary-low-read ((((class color) (min-colors 256)) (:foreground "#becccc"))))
 '(gnus-summary-low-ticked ((((class color) (min-colors 256)) (:foreground "#9f74bb"))))
 '(gnus-summary-low-unread ((((class color) (min-colors 256)) (:foreground "#88b06c"))))
 '(gnus-summary-normal-ancient ((((class color) (min-colors 256)) (:foreground "#A8A8A8" :inherit 'italic))))
 '(gnus-summary-normal-read ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(gnus-summary-normal-ticked ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(gnus-summary-normal-unread ((((class color) (min-colors 256)) (:foreground "#ABDC88" :inherit 'bold))))
 '(gnus-summary-selected ((((class color) (min-colors 256)) (:foreground "#82AAFF" :weight bold))))
 '(gnus-cite-1 ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(gnus-cite-2 ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(gnus-cite-3 ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(gnus-cite-4 ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(gnus-cite-5 ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(gnus-cite-6 ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(gnus-cite-7 ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(gnus-cite-8 ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(gnus-cite-9 ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(gnus-cite-10 ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(gnus-cite-11 ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(gnus-signature ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(gnus-x-face ((((class color) (min-colors 256)) (:background "#A8A8A8" :foreground "#EEFFFF"))))
 '(notmuch-crypto-decryption ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(notmuch-crypto-signature-bad ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(notmuch-crypto-signature-good ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(notmuch-crypto-signature-good-key ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(notmuch-crypto-signature-unknown ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(notmuch-message-summary-face ((((class color) (min-colors 256)) (:background "#202020" :overline "#626262"))))
 '(notmuch-search-count ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(notmuch-search-date ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(notmuch-search-flagged-face ((((class color) (min-colors 256)) (:foreground "#C792EA" :weight bold))))
 '(notmuch-search-matching-authors ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(notmuch-search-non-matching-authors ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(notmuch-search-subject ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(notmuch-search-unread-face ((((class color) (min-colors 256)) (:weight bold))))
 '(notmuch-tag-added ((((class color) (min-colors 256)) (:foreground "#ABDC88" :weight normal))))
 '(notmuch-tag-deleted ((((class color) (min-colors 256)) (:foreground "#FF7B85" :weight normal))))
 '(notmuch-tag-face ((((class color) (min-colors 256)) (:foreground "#FFCA41" :weight normal))))
 '(notmuch-tag-flagged ((((class color) (min-colors 256)) (:foreground "#FFCA41" :weight normal))))
 '(notmuch-tag-unread ((((class color) (min-colors 256)) (:foreground "#FFCA41" :weight normal))))
 '(notmuch-tree-match-author-face ((((class color) (min-colors 256)) (:foreground "#82AAFF" :weight bold))))
 '(notmuch-tree-match-date-face ((((class color) (min-colors 256)) (:foreground "#FF996B" :weight bold))))
 '(notmuch-tree-match-face ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(notmuch-tree-match-subject-face ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(notmuch-tree-match-tag-face ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(notmuch-tree-match-tree-face ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(notmuch-tree-no-match-author-face ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(notmuch-tree-no-match-date-face ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(notmuch-tree-no-match-face ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(notmuch-tree-no-match-subject-face ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(notmuch-tree-no-match-tag-face ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(notmuch-tree-no-match-tree-face ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(notmuch-wash-cited-text ((((class color) (min-colors 256)) (:foreground "#BFC7D5"))))
 '(notmuch-wash-toggle-button ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(erc-button ((((class color) (min-colors 256)) (:weight bold :underline t))))
 '(erc-default-face ((((class color) (min-colors 256)) (:inherit 'default))))
 '(erc-action-face ((((class color) (min-colors 256)) (:weight bold))))
 '(erc-command-indicator-face ((((class color) (min-colors 256)) (:weight bold))))
 '(erc-direct-msg-face ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(erc-error-face ((((class color) (min-colors 256)) (:inherit 'error))))
 '(erc-header-line ((((class color) (min-colors 256)) (:background "#1b1b1b" :foreground "#89DDFF"))))
 '(erc-input-face ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(erc-current-nick-face ((((class color) (min-colors 256)) (:foreground "#ABDC88" :weight bold))))
 '(erc-timestamp-face ((((class color) (min-colors 256)) (:foreground "#82AAFF" :weight bold))))
 '(erc-nick-default-face ((((class color) (min-colors 256)) (:weight bold))))
 '(erc-nick-msg-face ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(erc-nick-prefix-face ((((class color) (min-colors 256)) (:inherit 'erc-nick-default-face))))
 '(erc-my-nick-face ((((class color) (min-colors 256)) (:foreground "#ABDC88" :weight bold))))
 '(erc-my-nick-prefix-face ((((class color) (min-colors 256)) (:inherit 'erc-my-nick-face))))
 '(erc-notice-face ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(erc-prompt-face ((((class color) (min-colors 256)) (:foreground "#89DDFF" :weight bold))))
 '(evil-ex-info ((((class color) (min-colors 256)) (:foreground "#FF7B85" :slant italic))))
 '(evil-ex-search ((((class color) (min-colors 256)) (:background "#303030" :foreground "#89DDFF" :weight bold))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 256)) (:background "#303030" :foreground "#FF7B85" :weight bold :strike-through t))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 256)) (:background "#303030" :foreground "#ABDC88" :weight bold))))
 '(evil-search-highlight-persist-highlight-face ((((class color) (min-colors 256)) (:inherit 'lazy-highlight))))
 '(evil-mc-cursor-default-face ((((class color) (min-colors 256)) (:background "#C792EA" :foreground "#303030" :inverse-video nil))))
 '(evil-mc-region-face ((((class color) (min-colors 256)) (:inherit 'region))))
 '(evil-mc-cursor-bar-face ((((class color) (min-colors 256)) (:height 1 :background "#C792EA" :foreground "#303030"))))
 '(evil-mc-cursor-hbar-face ((((class color) (min-colors 256)) (:underline `(:color ,cyan)))))
 '(evil-snipe-first-match-face ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#41557f" :weight bold))))
 '(evil-snipe-matches-face ((((class color) (min-colors 256)) (:foreground "#89DDFF" :underline t :weight bold))))
 '(evil-goggles-delete-face ((((class color) (min-colors 256)) (:foreground "#7f3d42" :background "#FF7B85"))))
 '(evil-goggles-paste-face ((((class color) (min-colors 256)) (:foreground "#556e44" :background "#ABDC88"))))
 '(evil-goggles-undo-redo-add-face ((((class color) (min-colors 256)) (:inherit 'evil-goggles-paste-face))))
 '(evil-goggles-undo-redo-remove-face ((((class color) (min-colors 256)) (:inherit 'evil-goggles-delete-face))))
 '(evil-goggles-record-macro-face ((((class color) (min-colors 256)) (:foreground "#7f6520" :background "#FFCA41"))))
 '(font-lock-warning-face ((((class color) (min-colors 256)) (:inherit 'warning))))
 '(font-lock-function-name-face ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(font-lock-keyword-face ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(font-lock-comment-face ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(font-lock-type-face ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(font-lock-constant-face ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(font-lock-builtin-face ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(font-lock-string-face ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(font-lock-doc-face ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(goggles-changed ((((class color) (min-colors 256)) (:background "#89DDFF"))))
 '(goggles-added ((((class color) (min-colors 256)) (:background "#ABDC88"))))
 '(goggles-removed ((((class color) (min-colors 256)) (:background "#FF7B85"))))
 '(hydra-face-red ((((class color) (min-colors 256)) (:foreground "#FF7B85" :weight bold))))
 '(hydra-face-blue ((((class color) (min-colors 256)) (:foreground "#82AAFF" :weight bold))))
 '(hydra-face-amaranth ((((class color) (min-colors 256)) (:foreground "#C792EA" :weight bold))))
 '(hydra-face-pink ((((class color) (min-colors 256)) (:foreground "#BB80B3" :weight bold))))
 '(hydra-face-teal ((((class color) (min-colors 256)) (:foreground "#44b9b1" :weight bold))))
 '(icomplete-section ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(icomplete-first-match ((((class color) (min-colors 256)) (:foreground "#ABDC88" :weight bold :underline t))))
 '(icomplete-selected-match ((((class color) (min-colors 256)) (:weight bold :underline t :extend t))))
 '(inf-ruby-result-overlay-face ((((class color) (min-colors 256)) (:foreground "#89DDFF" :background "#202020" :box (:line-width 1 :color "#89DDFF")))))
 '(isearch ((((class color) (min-colors 256)) (:inherit 'match :weight bold))))
 '(isearch-fail ((((class color) (min-colors 256)) (:background "#FF7B85" :foreground "#303030" :weight bold))))
 '(keycast-key ((((class color) (min-colors 256)) (:weight bold :background "#ABDC88" :foreground "#151515"))))
 '(keycast-command ((((class color) (min-colors 256)) (:foreground "#ABDC88" :weight bold))))
 '(flymake-error ((((class color) (min-colors 256)) (:underline (:style wave :color "#FF7B85")))))
 '(flymake-note ((((class color) (min-colors 256)) (:underline (:style wave :color "#ABDC88")))))
 '(flymake-warning ((((class color) (min-colors 256)) (:underline (:style wave :color "#FF996B")))))
 '(flycheck-error ((((class color) (min-colors 256)) (:underline (:style wave :color "#FF7B85")))))
 '(flycheck-warning ((((class color) (min-colors 256)) (:underline (:style wave :color "#FFCA41")))))
 '(flycheck-info ((((class color) (min-colors 256)) (:underline (:style wave :color "#ABDC88")))))
 '(flycheck-fringe-error ((((class color) (min-colors 256)) (:inherit 'fringe :foreground "#FF7B85"))))
 '(flycheck-fringe-warning ((((class color) (min-colors 256)) (:inherit 'fringe :foreground "#FFCA41"))))
 '(flycheck-fringe-info ((((class color) (min-colors 256)) (:inherit 'fringe :foreground "#ABDC88"))))
 '(flycheck-posframe-face ((((class color) (min-colors 256)) (:inherit 'default))))
 '(flycheck-posframe-background-face ((((class color) (min-colors 256)) (:background "#202020"))))
 '(flycheck-posframe-error-face ((((class color) (min-colors 256)) (:inherit 'flycheck-posframe-face :foreground "#FF7B85"))))
 '(flycheck-posframe-info-face ((((class color) (min-colors 256)) (:inherit 'flycheck-posframe-face :foreground "#EEFFFF"))))
 '(flycheck-posframe-warning-face ((((class color) (min-colors 256)) (:inherit 'flycheck-posframe-face :foreground "#FFCA41"))))
 '(flyspell-incorrect ((((class color) (min-colors 256)) (:underline (:style wave :color "#FF7B85") :inherit 'unspecified))))
 '(flyspell-duplicate ((((class color) (min-colors 256)) (:underline (:style wave :color "#FFCA41") :inherit 'unspecified))))
 '(eglot-highlight-symbol-face ((((class color) (min-colors 256)) (:weight bold :background "#303030"))))
 '(eldoc-box-border ((((class color) (min-colors 256)) (:background "#303030"))))
 '(lsp-ui-doc-background ((((class color) (min-colors 256)) (:background "#202020"))))
 '(lsp-ui-doc-header ((((class color) (min-colors 256)) (:foreground "#ABDC88" :underline t))))
 '(meow-search-indicator ((((class color) (min-colors 256)) (:foreground "#FFCA41" :weight bold))))
 '(meow-search-highlight ((((class color) (min-colors 256)) (:foregound "#EEFFFF" :background "#a5832a" :weight bold))))
 '(mode-line ((((class color) (min-colors 256)) (:foreground "#BFC7D5" :background "#202020" :box (:line-width (2 . 2) :color "#303030" :style flat-button)))))
 '(mode-line-inactive ((((class color) (min-colors 256)) (:inherit 'mode-line :foreground "#626262" :background "#151515"))))
 '(mode-line-highlight ((((class color) (min-colors 256)) (:box (:line-width (2 . 2) :color "#C792EA")))))
 '(mode-line-buffer-id ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :weight bold))))
 '(orderless-match-face-0 ((((class color) (min-colors 256)) (:weight bold :foreground "#82AAFF"))))
 '(orderless-match-face-1 ((((class color) (min-colors 256)) (:weight bold :foreground "#FFCA41"))))
 '(orderless-match-face-2 ((((class color) (min-colors 256)) (:weight bold :foreground "#C792EA"))))
 '(orderless-match-face-3 ((((class color) (min-colors 256)) (:weight bold :foreground "#ABDC88"))))
 '(org-block ((((class color) (min-colors 256)) (:background "#202020"))))
 '(org-block-background ((((class color) (min-colors 256)) (:background "#202020"))))
 '(org-block-begin-line ((((class color) (min-colors 256)) (:foreground "#626262" :background "#151515"))))
 '(org-level-1 ((((class color) (min-colors 256)) (:inherit bold :foreground "#ABDC88"))))
 '(org-level-2 ((((class color) (min-colors 256)) (:inherit bold :foreground "#FFCA41"))))
 '(org-level-3 ((((class color) (min-colors 256)) (:inherit bold :foreground "#FF7B85"))))
 '(org-level-4 ((((class color) (min-colors 256)) (:inherit bold :foreground "#89DDFF"))))
 '(org-level-5 ((((class color) (min-colors 256)) (:inherit bold :foreground "#82AAFF"))))
 '(org-level-6 ((((class color) (min-colors 256)) (:inherit bold :foreground "#C792EA"))))
 '(org-level-7 ((((class color) (min-colors 256)) (:inherit bold :foreground "#44b9b1"))))
 '(org-level-8 ((((class color) (min-colors 256)) (:inherit bold :foreground "#BB80B3"))))
 '(org-headline-done ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(org-table ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(org-todo ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(org-done ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(org-drawer ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(org-meta-line ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(org-special-keyword ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(org-property-value ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(org-tag ((((class color) (min-colors 256)) (:foreground "#BFC7D5"))))
 '(org-verbatim ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(org-code ((((class color) (min-colors 256)) (:foreground "#FF996B" :background "#202020"))))
 '(org-document-info-keyword ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(org-document-info ((((class color) (min-colors 256)) (:foreground "#BFC7D5"))))
 '(org-document-title ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(org-date ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(org-checkbox ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(org-checkbox-statistics-todo ((((class color) (min-colors 256)) (:inherit 'org-checkbox))))
 '(org-checkbox-statistics-done ((((class color) (min-colors 256)) (:inherit 'org-done))))
 '(org-agenda-done ((((class color) (min-colors 256)) (:inherit 'org-done))))
 '(org-agenda-clocking ((((class color) (min-colors 256)) (:background "#446e7f" :extend t))))
 '(org-time-grid ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(org-imminent-deadline ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(org-upcoming-deadline ((((class color) (min-colors 256)) (:foreground "#44b9b1"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(org-habit-clear-face ((((class color) (min-colors 256)) (:weight bold :background "#626262"))))
 '(org-habit-clear-future-face ((((class color) (min-colors 256)) (:weight bold :background "#A8A8A8"))))
 '(org-habit-ready-face ((((class color) (min-colors 256)) (:weight bold :background "#41557f"))))
 '(org-habit-ready-future-face ((((class color) (min-colors 256)) (:weight bold :background "#5a76b2"))))
 '(org-habit-alert-face ((((class color) (min-colors 256)) (:weight bold :background "#7f6520"))))
 '(org-habit-alert-future-face ((((class color) (min-colors 256)) (:weight bold :background "#b28d2d"))))
 '(org-habit-overdue-face ((((class color) (min-colors 256)) (:weight bold :background "#7f3d42"))))
 '(org-habit-overdue-future-face ((((class color) (min-colors 256)) (:weight bold :background "#b2565d"))))
 '(org-journal-highlight ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(org-journal-calendar-entry-face ((((class color) (min-colors 256)) (:foreground "#C792EA" :slant italic))))
 '(org-journal-calendar-scheduled-face ((((class color) (min-colors 256)) (:foreground "#FF7B85" :slant italic))))
 '(org-pomodoro-mode-line ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(org-pomodoro-mode-line-overtime ((((class color) (min-colors 256)) (:foreground "#FFCA41" :weight bold))))
 '(org-mode-line-clock ((((class color) (min-colors 256)) (:foreground "#EEFFFF"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 256)) (:inherit error))))
 '(org-ref-acronym-face ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(org-ref-cite-face ((((class color) (min-colors 256)) (:foreground "#FFCA41" :weight light :underline t))))
 '(org-ref-glossary-face ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(org-ref-label-face ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(org-ref-ref-face ((((class color) (min-colors 256)) (:inherit 'link :foreground "#44b9b1"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 256)) (:foreground "#44b9b1"))))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(reb-match-0 ((((class color) (min-colors 256)) (:foreground "#ABDC88" :background "#556e44"))))
 '(reb-match-1 ((((class color) (min-colors 256)) (:foreground "#89DDFF" :background "#446e7f"))))
 '(reb-match-2 ((((class color) (min-colors 256)) (:foreground "#FFCA41" :background "#7f6520"))))
 '(reb-match-3 ((((class color) (min-colors 256)) (:foreground "#C792EA" :background "#634975"))))
 '(rjsx-tag ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(rjsx-attr ((((class color) (min-colors 256)) (:foreground "#FFCA41" :slant italic :weight medium))))
 '(rjsx-tag-bracket-face ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(eshell-prompt ((((class color) (min-colors 256)) (:foreground "#C792EA" :weight bold))))
 '(eshell-ls-archive ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(eshell-ls-backup ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(eshell-ls-clutter ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(eshell-ls-directory ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(eshell-ls-executable ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(eshell-ls-missing ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(eshell-ls-product ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(eshell-ls-readonly ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(eshell-ls-special ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(eshell-ls-symlink ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(eshell-ls-unreadable ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(vterm-color-black ((((class color) (min-colors 256)) (:background "#303030" :foreground "#595959"))))
 '(vterm-color-red ((((class color) (min-colors 256)) (:background "#FF7B85" :foreground "#ff959d"))))
 '(vterm-color-green ((((class color) (min-colors 256)) (:background "#ABDC88" :foreground "#bbe39f"))))
 '(vterm-color-yellow ((((class color) (min-colors 256)) (:background "#FFCA41" :foreground "#ffd466"))))
 '(vterm-color-blue ((((class color) (min-colors 256)) (:background "#82AAFF" :foreground "#9bbbff"))))
 '(vterm-color-magenta ((((class color) (min-colors 256)) (:background "#C792EA" :foreground "#c899c2"))))
 '(vterm-color-cyan ((((class color) (min-colors 256)) (:background "#89DDFF" :foreground "#a0e3ff"))))
 '(vterm-color-white ((((class color) (min-colors 256)) (:background "#EEFFFF" :foreground "#A8A8A8"))))
 '(tab-line ((((class color) (min-colors 256)) (:background "#202020"))))
 '(tab-line-tab ((((class color) (min-colors 256)) (:background "#202020" :foreground "#BFC7D5"))))
 '(tab-line-tab-inactive ((((class color) (min-colors 256)) (:inherit 'tab-line-tab :background "#202020" :foreground "#626262"))))
 '(tab-line-tab-inactive-alternate ((((class color) (min-colors 256)) (:inherit 'tab-line-tab-inactive))))
 '(tab-line-tab-current ((((class color) (min-colors 256)) (:background "#202020" :foreground "#EEFFFF"))))
 '(tab-line-highlight ((((class color) (min-colors 256)) (:inherit 'tab-line-tab))))
 '(tab-line-close-highlight ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(tab-bar ((((class color) (min-colors 256)) (:inherit tab-line))))
 '(tab-bar-tab ((((class color) (min-colors 256)) (:inherit tab-line-tab))))
 '(tab-bar-tab-inactive ((((class color) (min-colors 256)) (:inherit tab-line-tab-inactive))))
 '(transpose-mark-region-set-face ((((class color) (min-colors 256)) (:background "#634975" :foreground "#C792EA" :weight bold))))
 '(typescript-jsdoc-tag ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(typescript-jsdoc-type ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(typescript-jsdoc-value ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(diff-added ((((class color) (min-colors 256)) (:foreground "#ABDC88" :background "#556e44"))))
 '(diff-changed ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#41557f"))))
 '(diff-context ((((class color) (min-colors 256)) (:foreground "#A8A8A8"))))
 '(diff-removed ((((class color) (min-colors 256)) (:foreground "#FF7B85" :background "#7f3d42"))))
 '(diff-header ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(diff-file-header ((((class color) (min-colors 256)) (:foreground "#82AAFF" :background "#151515"))))
 '(diff-hunk-header ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(diff-refine-added ((((class color) (min-colors 256)) (:inherit 'diff-added :inverse-video t))))
 '(diff-refine-changed ((((class color) (min-colors 256)) (:inherit 'diff-changed :inverse-video t))))
 '(diff-refine-removed ((((class color) (min-colors 256)) (:inherit 'diff-removed :inverse-video t))))
 '(diff-hl-change ((((class color) (min-colors 256)) (:background "#82AAFF" :foreground "#82AAFF"))))
 '(diff-hl-delete ((((class color) (min-colors 256)) (:background "#FF7B85" :foreground "#FF7B85"))))
 '(diff-hl-insert ((((class color) (min-colors 256)) (:background "#ABDC88" :foreground "#ABDC88"))))
 '(ediff-fine-diff-A ((((class color) (min-colors 256)) (:background "#66a1b8" :weight bold :extend))))
 '(ediff-fine-diff-B ((((class color) (min-colors 256)) (:inherit 'ediff-fine-diff-A))))
 '(ediff-fine-diff-C ((((class color) (min-colors 256)) (:inherit 'ediff-fine-diff-A))))
 '(ediff-current-diff-A ((((class color) (min-colors 256)) (:background "#37515b" :extend t))))
 '(ediff-current-diff-B ((((class color) (min-colors 256)) (:inherit 'ediff-current-diff-A))))
 '(ediff-current-diff-C ((((class color) (min-colors 256)) (:inherit 'ediff-current-diff-A))))
 '(ediff-even-diff-A ((((class color) (min-colors 256)) (:inherit 'hl-line))))
 '(ediff-even-diff-B ((((class color) (min-colors 256)) (:inherit 'ediff))))
 '(ediff-even-diff-C ((((class color) (min-colors 256)) (:inherit 'ediff-even-diff-A))))
 '(ediff-odd-diff-A ((((class color) (min-colors 256)) (:inherit 'ediff-even-diff-A))))
 '(ediff-odd-diff-B ((((class color) (min-colors 256)) (:inherit 'ediff-odd-diff-A))))
 '(ediff-odd-diff-C ((((class color) (min-colors 256)) (:inherit 'ediff-odd-diff-A))))
 '(magit-bisect-bad ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(magit-bisect-good ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(magit-bisect-skip ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(magit-blame-hash ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(magit-blame-date ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(magit-blame-heading ((((class color) (min-colors 256)) (:foreground "#FF996B" :background "#202020" :extend t))))
 '(magit-branch-current ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(magit-branch-local ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(magit-branch-remote ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(magit-cherry-equivalent ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(magit-cherry-unmatched ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(magit-diff-added ((((class color) (min-colors 256)) (:foreground "#88b06c" :background "#242820" :extend t))))
 '(magit-diff-added-highlight ((((class color) (min-colors 256)) (:foreground "#ABDC88" :background "#333c2c" :weight bold :extend t))))
 '(magit-diff-base ((((class color) (min-colors 256)) (:foreground "#cc7a55" :background "#2c221d" :extend t))))
 '(magit-diff-base-highlight ((((class color) (min-colors 256)) (:foreground "#FF996B" :background "#432f26" :weight bold :extend t))))
 '(magit-diff-context ((((class color) (min-colors 256)) (:foreground "#8e9999" :background "#151515" :extend t))))
 '(magit-diff-context-highlight ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :background "#202020" :extend t))))
 '(magit-diff-file-heading ((((class color) (min-colors 256)) (:foreground "#EEFFFF" :weight bold :extend t))))
 '(magit-diff-file-heading-selection ((((class color) (min-colors 256)) (:foreground "#C792EA" :background "#41557f" :weight bold :extend t))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 256)) (:foreground "#151515" :background "#463544" :extend t))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 256)) (:foreground "#151515" :background "#BB80B3" :weight bold :extend t))))
 '(magit-diff-lines-heading ((((class color) (min-colors 256)) (:foreground "#FFCA41" :background "#FF7B85" :extend t :extend t))))
 '(magit-diff-removed ((((class color) (min-colors 256)) (:foreground "#cc626a" :background "#2c1f20" :extend t))))
 '(magit-diff-removed-highlight ((((class color) (min-colors 256)) (:foreground "#FF7B85" :background "#43292b" :weight bold :extend t))))
 '(magit-diffstat-added ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(magit-diffstat-removed ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(magit-dimmed ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(magit-hash ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(magit-header-line ((((class color) (min-colors 256)) (:background "#202020" :foreground "#FFCA41" :weight bold))))
 '(magit-filename ((((class color) (min-colors 256)) (:foreground "#BB80B3"))))
 '(magit-log-author ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(magit-log-date ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(magit-log-graph ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(magit-process-ng ((((class color) (min-colors 256)) (:inherit 'error))))
 '(magit-process-ok ((((class color) (min-colors 256)) (:inherit 'success))))
 '(magit-reflog-amend ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(magit-reflog-checkout ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(magit-reflog-commit ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(magit-reflog-merge ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(magit-reflog-other ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(magit-reflog-rebase ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(magit-reflog-remote ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(magit-reflog-reset ((((class color) (min-colors 256)) (:inherit 'error))))
 '(magit-refname ((((class color) (min-colors 256)) (:foreground "#626262"))))
 '(magit-section-heading ((((class color) (min-colors 256)) (:foreground "#82AAFF" :weight bold :extend t))))
 '(magit-section-heading-selection ((((class color) (min-colors 256)) (:foreground "#FF996B" :weight bold :extend t))))
 '(magit-section-highlight ((((class color) (min-colors 256)) (:inherit 'hl-line))))
 '(magit-section-secondary-heading ((((class color) (min-colors 256)) (:foreground "#BB80B3" :weight bold :extend t))))
 '(magit-sequence-drop ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(magit-sequence-head ((((class color) (min-colors 256)) (:foreground "#82AAFF"))))
 '(magit-sequence-part ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(magit-sequence-stop ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(magit-signature-bad ((((class color) (min-colors 256)) (:inherit 'error))))
 '(magit-signature-error ((((class color) (min-colors 256)) (:inherit 'error))))
 '(magit-signature-expired ((((class color) (min-colors 256)) (:foreground "#FF996B"))))
 '(magit-signature-good ((((class color) (min-colors 256)) (:inherit 'success))))
 '(magit-signature-revoked ((((class color) (min-colors 256)) (:foreground "#C792EA"))))
 '(magit-signature-untrusted ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(magit-tag ((((class color) (min-colors 256)) (:foreground "#FFCA41"))))
 '(markdown-code-face ((((class color) (min-colors 256)) (:inherit default))))
 '(markdown-list-face ((((class color) (min-colors 256)) (:inherit markdown-markup-face :height 0.65))))
 '(web-mode-html-tag-face ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(web-mode-html-attr-equal-face ((((class color) (min-colors 256)) (:foreground "#89DDFF"))))
 '(widget-button-pressed ((((class color) (min-colors 256)) (:foreground "#FF7B85"))))
 '(widget-documentation ((((class color) (min-colors 256)) (:foreground "#ABDC88"))))
 '(widget-single-line-field ((((class color) (min-colors 256)) (:background "#626262" :distant-foreground "#151515"))))
 '(widget-field ((((class color) (min-colors 256)) (:background "#626262" :distant-foreground "#151515" :box `(:line-width -1 :color ,grey1) :extend t))))
 '(default ((((class color) (min-colors 256)) (:background "#151515" :foreground "#EEFFFF"))))
 '(marginalia-documentation ((t (:foreground "#626262"))))
 '(persp-selected-face ((t (:foreground "#82AAFF" :weight bold)))))

 ;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'mod-tangonov)
